version: '3'

services:

  spark-master:
    image: custom-spark-scala2.13
    # image: bitnami/spark:3.4.1-scala2.13
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./.venv/lib/python3.9/site-packages/pyspark/jars:/opt/bitnami/spark/.ivy2/jars
      - .:/opt/bitnami/spark/app
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_CLASSPATH: /opt/bitnami/spark/.ivy2/jars/*:/opt/bitnami/spark/jars/*
      SPARK_JARS: /opt/bitnami/spark/jars/*  
      SPARK_PACKAGES: com.datastax.spark:spark-cassandra-connector_2.12:3.4.1
    networks:
      - confluent
  spark-worker:
    image: custom-spark-scala2.13
    # image: bitnami/spark:3.4.1-scala2.13
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./.venv/lib/python3.9/site-packages/pyspark/jars:/opt/bitnami/spark/.ivy2/jars
      - .:/opt/bitnami/spark/app
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_JARS: /opt/bitnami/spark/jars/*  
      SPARK_CLASSPATH: /opt/bitnami/spark/.ivy2/jars/*:/opt/bitnami/spark/jars/*
      SPARK_PACKAGES: com.datastax.spark:spark-cassandra-connector_2.12:3.4.1
    networks:
      - confluent

  cassandra_db:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - confluent

networks:
  confluent:
    external: true